version: "3"

services:
  
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: johndoe 
      POSTGRESa_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports: 
      - 5432:5432
  
  api:
    build: 
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - 4321:4321
